### ISSUE TITLE
More Mac shortcuts

### ISSUE THREAD

**Issue by aeschli** [waderyan/vscode-atom-keybindings#4]
Testing Microsoft/vscode#14318:

Going through http://sweetme.at/2014/03/10/atom-editor-cheat-sheet/ I found the following shortcuts that we could add as well:

Fold Code   `⌥-⌘-[` (-> editor.foldAll)
Unfold Code `⌥-⌘-]`   (-> editor.unfoldAll)
Convert Tabs to Spaces  `⌥-⌘-[` (-> editor.action.indentationToSpaces)
Convert Spaces to Tabs  `⌥-⌘-]` (-> editor.action.indentationToTabs)

Find Open File  `⌘-b`  (-> workbench.action.showAllEditors)

**Comment by pmbenjamin** [comment]
Also, Atom supports adding new files/directories in their explorer via keyboard shortcuts.
For example:
- In Atom, when File Explorer is in focus, key `a` will prompt the user to type a file name.
- In Atom, when File Explorer is in focus, key `A` (or `shift+a`) will prompt the user to type a directory name (relative to the current directory).

I would love to see these shortcuts ported over to VSCode as well. 
Since this is currently possible with the Command Palette in VSCode (see screenshot), I think this should be as simple as binding keyboard shortcuts to skip the Command Palette.
<img width="1916" alt="screen shot 2016-11-02 at 3 36 58 pm" src="https://cloud.githubusercontent.com/assets/6811830/19950116/c3f8011a-a112-11e6-8697-716fd080b927.png">


I foresee an implementation looking something like:
```
{
    "mac": "a",
    "win": "a",
    "linux": "a",
    "key": "a",
    "command": "workbench.files.action.createNewFile",
    "when": "explorerFocus"
},
{
    "mac": "shift+a",
    "win": "shift+a",
    "linux": "shift+a",
    "key": "shift+a",
    "command": "workbench.files.action.createNewFolder",
    "when": "explorerFocus"
}
```

#### Possible Challenges/Concerns with proposed implementation:
- I don't think VSCode supports `explorerFocus`
- I don't know what is the `command` used by the Command Palette to create new files and folders.

**Comment by waderyan** [comment]
Moved these to separate issues to better track the work. 

https://github.com/waderyan/vscode-atom-keybindings/issues/21
https://github.com/waderyan/vscode-atom-keybindings/issues/18
https://github.com/waderyan/vscode-atom-keybindings/issues/19
https://github.com/waderyan/vscode-atom-keybindings/issues/20
